services:
  - type: cron
    name: bigtelemarketing-bot
    schedule: "0 7,13,18 * * 1-5"  # Lun-Ven alle 09:00, 15:00, 20:00 (ora italiana)
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
